# Generated by Django 4.1.7 on 2024-10-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('contenido', models.CharField(max_length=500)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField()),
                ('dislike', models.IntegerField()),
            ],
        ),
    ]
